### ISSUE TITLE
"Deselect" X was out of place when the interface was shown on the PLSE projector screen

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#131]
Probably due to the small display size?

**Comment by jaelafield** [comment]
I'm not able to replicate this anymore. I did make a sizing [change](https://github.com/herbie-fp/odyssey/commit/2e87985366cfd804f9da96680e8ca34b49654ab7) a while back, but it wasn't especially sophisticated.

**Comment by jaelafield** [comment]
Ideal situation is implementing selected point in classic html layered on top of the plot rather than as part of an svg. There are limitations with svgs in the styling capabilities (no flexbox) which is what creates problems like this since it relies on particular x, y dimensions relative to the outer svg. 

Current implementation was a result of needing to set z-index attributes which broke the whole Odyssey UI, but I didn't explore what it would take to make it compatible much.

**Comment by elmisback** [comment]
For future reference, flexbox works in SVGs if you use a foreignobject, like this:
![image](https://github.com/user-attachments/assets/492d29c4-91ce-4a72-bf60-74f5c438a62a)

Sizing of the foreignObject will still be fixed I think though
