### ISSUE TITLE
Prep FPTaylor example

### ISSUE THREAD

**Issue by elmisback** [herbie-fp/odyssey#176]

**Comment by elmisback** [comment]
Please put Artem's response here

**Comment by benwang33** [comment]
(Artem's paraphrased response below)

For Linear benchmarks, their inputs can be reduced to [0,1e20] and it may work

Link to Example: https://github.com/AYadrov/FPGuard/blob/master/Benchmarks/nonline-interpolation/SAT/interpol.txt
Photo of Example: 
![Image](https://github.com/user-attachments/assets/7eafb7a6-efad-44f8-acac-0cc8d35b0657)


Or, probably, a better idea is to go through FPTaylor's examples, like this one:
![Image](https://github.com/user-attachments/assets/47ca3c0f-6e69-4391-84a0-fa854d975c74)

You can rewrite it to FPCore and run in Herbie

Can check out other examples on their website: https://monadius.github.io/FPTaylorJS/#/ 

I think that you can neglect Bounds and focus more on the absolute error, since it is more important. FPTaylor, for some reasons, has infinite bounds even for simple programs

**Comment by elmisback** [comment]
Use FPTaylor paper example!

**Comment by benwang33** [comment]
cos example from Artem
Link: https://monadius.github.io/FPTaylorJS/#/
